# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Findr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Findr
  pod 'SnapKit'
  pod 'SwiftVideoBackground'
  pod 'PopupDialog', '~> 1.1'
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git'

end
